version: '3.3'

networks:
  friendos-network:
    external: true

services:
  friendos:
    build:
      context: .
      dockerfile: Dockerfile
    image: friendos-docker
    container_name: friendos-docker-container
    ports:
      - "16502:6502"
      - "16500:6500"
    networks:
      - friendos-network

